# Generated by Django 3.0.7 on 2020-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
